export const environment = {
  production: false,
  region: 'us-east-1',
  identityPoolId: 'us-east-1:010ab5fe-ba6a-4ef4-a910-9a24e8652a10',
  userPoolId: 'us-east-1_V2WlcIaSW',
  clientId: '2bkb3gmss24lo3fa44sbr4p35v',


  rekognitionBucket: '',
  albumName: '',
  bucketRegion: '',
  bucketName: 'neoapp-platform-data',

  ddbTableName: '',

  cognito_idp_endpoint: '',
  cognito_identity_endpoint: '',
  sts_endpoint: '',
  dynamodb_endpoint: '',
  s3_endpoint: '',

  dal_api_key: 'CqXdHADhwd36AT4URw3hm4IEIanQD0bB157qbQ2V',

  readApi: 'https://b6y05u8v66.execute-api.us-east-1.amazonaws.com/neoapp/v1/read',
  createApi: 'https://b6y05u8v66.execute-api.us-east-1.amazonaws.com/neoapp/v1/create',
  updateApi: 'https://b6y05u8v66.execute-api.us-east-1.amazonaws.com/neoapp/v1/update',
  deleteApi: 'https://b6y05u8v66.execute-api.us-east-1.amazonaws.com/neoapp/v1/delete',
  spend_data: 'https://xvzejhbk53.execute-api.us-east-1.amazonaws.com/neoApp/spend-data',
  spend_vis_data: 'https://efw82fei12.execute-api.us-east-1.amazonaws.com/neoApp/spendvisdata',
  spend_less_data: 'https://xvzejhbk53.execute-api.us-east-1.amazonaws.com/neoApp/spend-data',
  customDeleteApi: 'https://h1o8glpmjb.execute-api.us-east-1.amazonaws.com/neoapp/delete-rule',
  generateApi: 'https://lzg0voku2j.execute-api.us-east-1.amazonaws.com/neoapp/generate-recommendations',
  virtual_device_API: 'https://ol7eft3fp1.execute-api.us-east-1.amazonaws.com/v1/virtual-device',

  download_S3_Api: 'https://m8xio41sje.execute-api.us-east-1.amazonaws.com/neoapp/',
  x_api_key: '5OjNSr9qGO8OLwIPxfOjo1Rd7W76ZH191ON1WUKl',

  FILE_ALERTS: 'NeoApp_FILE_ALERTS',
  NEO_SITE: 'NeoApp_NEO_SITE',
  NEO_FEED: 'NeoApp_NEO_FEED',
  NEO_GEOGRAPHY: 'NeoApp_NEO_GEOGRAPHY',
  EMR_FILE_SUMMARY: 'NeoApp_EMR_FILE_SUMMARY',
  IOT_HARI_AQDATA: 'NeoApp_IOT_HARI_AQDATA',
  PB_WIDGETS: 'NeoApp_PB_WIDGETS',
  PB_DASHBOARD: 'NeoApp_PB_DASHBOARD',
  NEO_DEVICE_CONFIG: 'NeoApp_NEO_DEVICE_CONFIG',
  NEO_SORT_ZDATA: 'NeoApp_NEO_SORT_ZDATA',
  NEO_DATA_DICTIONARY: 'NeoApp_NEO_DATA_DICTIONARY',
  NEO_FILE_CONFIG: 'NeoApp_NEO_FILE_CONFIG',
  PROCESSED_FILES: 'NeoApp_PROCESSED_FILES',
  FILE_STATUS: 'NeoApp_FILE_STATUS',
  FILE_LINEAGE: 'NeoApp_FILE_LINEAGE',
  TRANSFORMATION_LINEAGE: 'NeoApp_TRANSFORMATION_LINEAGE',
  VALIDATION_RESULT: 'NeoApp_VALIDATION_RESULT',
  NEO_FILE_UPLOAD_LOGGS: 'NeoApp_NEO_FILE_UPLOAD_LOGGS',
  NEO_FOLDER_ACCESS: 'NeoApp_NEO_FOLDER_ACCESS',
  NEO_S3_ACCESS: 'NeoApp_NEO_S3_ACCESS',
  EMR_STEP_CONFIG_MASTER: 'NeoApp_EMR_STEP_CONFIG_MASTER',
  EMR_PROVISION_LOGS: 'NeoApp_EMR_PROVISION_LOGS',
  DATA_PREPROCESSING_RULES: 'NeoApp_DATA_PREPROCESSING_RULES',
  DATA_PREPROCESSING_SUMMARY: 'NeoApp_DATA_PREPROCESSING_SUMMARY',
  DATA_SUGGESTIONS: 'NeoApp_DATA_SUGGESTIONS',
  PROFILING_DIGEST: 'NeoApp_PROFILING_DIGEST',
  PROFILING_ABSTRACT: 'NeoApp_PROFILING_ABSTRACT',
  STEP_FUNCTION_EVENTS: 'NeoApp_STEP_FUNCTION_EVENTS',
  TRANSFORMATION_CONFIG: 'NeoApp_TRANSFORMATION_CONFIG',
  TRANSFORMATION_MAPPINGS: 'NeoApp_TRANSFORMATION_MAPPINGS',
  NEO_ROLE_ACCESS: 'NeoApp_NEO_ROLE_ACCESS',
  NEO_UI_MENU: 'NeoApp_NEO_UI_MENU',
  NEO_USER_LIST: 'NeoApp_NEO_USER_LIST',
  VTS_RouteAdherence: 'NeoApp_VTS_RouteAdherence',
  VTS_Attendance: 'NeoApp_VTS_Attendance',
  VTS_Speed: 'NeoApp_VTS_Speed',
  VTS_Distance: 'NeoApp_VTS_Distance',
  NEO_ZENATIX_AGGREGATION: 'NeoApp_NEO_ZENATIX_AGGREGATION',
  NEO_DAILY_ZENATIX_AGGREGATION: 'NeoApp_NEO_DAILY_ZENATIX_AGGREGATION',
  NEO_ZENATIX_ALL: 'NeoApp_NEO_ZENATIX_ALL'

};
